name: Terraform CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      action:
        description: 'Type "apply" to deploy or "destroy" to remove infrastructure'
        required: true
        default: 'apply'

env:
  GCP_KB_PODS_SA: ${{ secrets.GCP_KB_PODS_SA }}

jobs:
  setup:
    runs-on: ubuntu-latest
      - name: Create Kafka Producer ServiceAccount YAML
        run: |
          echo "apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: kafka-producer-sa
            namespace: kafka
            annotations:
              iam.gke.io/gcp-service-account: \"${GCP_KB_PODS_SA}\"" > kafka-sa-producer.yaml
        env:
          GCP_KB_PODS_SA: ${{ secrets.GCP_KB_PODS_SA }}
      - name: Create Kafka echo variable
         run: |
           echo kafka-sa-producer.yaml
